config/routes.rb
Rails.application.routes.draw do

  resources :tasks, only: :index

  resources :users do
    scope module: :users do
      resources :tasks do
        post 'state', on: :member
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  include AASM

  aasm :column => 'state' do
    state :new, initial: true
    state :started, :finished
  end

  mount_uploader :file, FileUploader

  belongs_to :user

  default_scope { order(created_at: :desc) }

  validates :user, :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  include AASM

  aasm :column => 'role' do
    state :user, initial: true
    state :admin
  end

  has_many :tasks

  default_scope { order(email: :asc) }

  validates :email, presence: true,
                    uniqueness: true,
                    length: {:minimum => 4, :maximum => 254},
                    format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}

  def to_s
    self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'signin'

  def new
  end

  def create
    user = User.find_by_email(params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      redirect_to user_tasks_path(user), notice: 'Вы вошли в систему.'
    else
      flash[:alert] = 'Неверные почта или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Вы вышли из системы.'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/controllers/users/tasks_controller.rb
class Users::TasksController < ApplicationController
  def index
    if current_user.admin?
      @tasks = Task.all
    else
      @tasks = Task.where(user_id: params[:user_id])
    end
  end

  def state
    @task = Task.find(params[:id])
    @task.state = params[:state]
    @task.save
    redirect_to user_tasks_path, notice: 'Статус задачи обновлён'
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to user_tasks_path, notice: 'Задача создана.'
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    authorize @task
    if @task.update(task_params)
      redirect_to user_tasks_path, notice: 'Задача обновлена.'
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    authorize @task
    @task.destroy
    redirect_to user_tasks_path, notice: 'Задача удалена.'
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :state, :file, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def link_or_image(object)
    if (object.file.content_type.split('/')[0] == 'image')
      image_tag object.file.url
    else
      link_to object.file_identifier, object.file.url
    end
  end
end

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title TaskManager
    = stylesheet_link_tag  'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'TaskManager', root_path, :class => 'navbar-brand'
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Задачи', root_path
            - if current_user
              %li
                = link_to 'Мои задачи', user_tasks_path(current_user)
          %ul.nav.navbar-nav.navbar-right
            %li
              - if current_user
                = link_to 'Выйти', session_path(current_user), method: :delete
              - else
                = link_to 'Войти', new_session_path
    / /.nav-collapse
    .container
      = render 'layouts/messages'
      = yield
      / Site footer
      %footer.footer
        %p

app/views/layouts/signin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title TaskManager
    = stylesheet_link_tag    'application', 'signin', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/messages'
      = yield
      / Site footer

app/views/tasks/index.html.haml
.page-header
  %h1 Все задачи

%table.table
  %thead
    %tr
      %th #
      %th Название
      %th Описание
      %th Статус
      %th Создана
      %th Назначена
  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.id
        %td= task.name
        %td= task.description
        %td= task.state
        %td= task.created_at.to_s(:short)
        %td= task.user.email

app/views/users/tasks/_form.html.haml
= simple_form_for [current_user, @task], html: { multipart: true } do |f|
  .row
    .col-sm-6
      = f.input :name
    .col-sm-6
      = f.input :state, as: :select, collection: Task.aasm.states_for_select, include_blank: false
  .row
    .col-sm-12
      = f.input :description
  .row
    .col-sm-6
      = f.input :file
    .col-sm-6
      - if current_user.admin?
        = f.association :user, include_blank: false
      - else
        = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
  - if @task.file?
    .form-group.row
      .col-sm-12
        = link_or_image(@task)
  .form-actions
    = link_to 'Отмена', :back, class:'btn btn-default'
    =f.button :submit, 'Сохранить', class:'btn btn-success'

app/views/users/tasks/edit.html.haml
.page-header
  %h1
    = link_to 'Мои задачи', user_tasks_path(current_user)
    \/ Правка задачи

= render 'form'

app/views/users/tasks/index.html.haml
.page-header
  %h1 Мои задачи
  %small= link_to 'Новая задача', new_user_task_path(current_user), class: 'btn btn-success p'

%table.table
  %thead
    %tr
      %th #
      %th Название
      %th Описание
      %th Статус
      %th Создана
      - if current_user.admin?
        %th
          Назначена
      %th
  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.id
        %td= link_to task.name, user_task_path(current_user, task)
        %td= task.description
        %td
          - if current_user.admin?
            = form_tag state_user_task_path(current_user, task), method: :post do
              = select_tag :state, options_for_select(Task.aasm.states_for_select, task.state),
                          class: 'state_list', :onchange => "this.form.submit()"
          - else
            = task.state
        %td= task.created_at.to_s(:db)
        - if current_user.admin?
          %td= task.user.email
        %td
          -if policy(task).update?
            = link_to edit_user_task_path(current_user, task), title: 'Редактировать' do
              %i.fa.fa-pencil.fa-1g
          &nbsp;
          -if policy(task).destroy?
            = link_to user_task_path(current_user, task), method: :delete, title: 'Удалить',
                      data: { confirm: 'Удалить задачу?' } do
              %i.fa.fa-close.fa-1g
  :javascript
    $(function () {
      $('.state_list').on('change', function(){
        $('.state_list').submit()
      });
    });

app/views/users/tasks/new.html.haml
.page-header
  %h1
    = link_to 'Мои задачи', user_tasks_path(current_user)
    \/ Новая задача

= render 'form'

app/views/users/tasks/show.html.haml
.page-header
  %h1
    = link_to 'Мои задачи', user_tasks_path(current_user)
    \/ Задача #
    = @task.id

.panel.panel-primary
  .panel-heading
    %h3.panel-title
      Задача:
      = @task.name
      &nbsp;
      = link_to edit_user_task_path(current_user, @task), title: 'Редактировать' do
        %i.fa.fa-pencil
  .panel-body
    .row
      .col-sm-4
        %h4
          Создана:
          = @task.created_at.to_s(:db)
      .col-sm-4
        %h4
          Статус:
          = @task.state.humanize
      .col-sm-4
        - if current_user.admin?
          %h4
            Назначена:
            = @task.user.email
    %h4 Описание:
    %blockquote= @task.description
    - if @task.file?
      %h4 Файл:
      %blockquote
        = link_or_image(@task)